version: 2

sources:
  - name: fellowship_24_25_data
    schema: fellowship_24_25
    tables:
      - name: Raw_Data_Baseline
        identifier: Raw_Data_sample
        description: This is a placeholder table & will be replaced with original. This table contains data of the baseline assessment for AY 24-25, for students in all classrooms. This table contains combined data for RF,RC & Math. This table comes from the master G-Sheet 'Baseline 2024_Overall Analysis'
      - name: Raw_Data_Midline
        identifier: Raw_Data_Midline
        description: This table contains data of the midline assessment for AY 24-25, for students in all classrooms. This table contains combined data for RF,RC & Math. This table comes from the master G-Sheet 'Midline 2024_Overall Analysis'
      - name: Raw_Data_Endline
        identifier: Raw_Data_Endline
        description: This table contains data of the endline assessment for AY 24-25, for students in all classrooms. This table contains combined data for RF,RC & Math. This table comes from the master G-Sheet 'Endline 2025_Overall data'
   
  - name: ecochamps25_26
    schema: ecochamps25_26
    tables:
      - name: Student___Session_Data
        identifier: Student___Session_Data
        description: This is a placeholder table Eco Champs 25&26
      - name: Center_Coordiantors
        identifier: Center_Coordiantors
        description: Center_Coordiantors 
      - name: Data_Tracker
        identifier: Data_Tracker
        description: Data Tracker
      - name: RAG_Quarter_Params
        identifier: RAG_Quarter_Params
        description: Quarterwise RAG Parameters
  
  - name: fellowship_25_26
    schema: fellowship_25_26
    tables:
      - name: Raw_Data_Baseline_2025
        identifier: Raw_Data_Baseline_2025
        description: Baseline raw data for AY 25-26 (source file/name in G-Sheet or staging area)
      - name: Raw_Data_Midline_2025
        identifier: Raw_Data_Midline_2025
        description: Midline raw data for AY 25-26 (source file/name in G-Sheet or staging area)

  - name: zc_bvms_data
    schema: ZC_BVMS_raw_data
    tables:
      - name: All_Session_Attendances
        identifier: All_Session_Attendances
        description: session attendances data
      - name: All_Session_Plannings
        identifier: All_Session_Plannings
        description: session planning data
      - name: Compass_All_Students
        identifier: Compass_All_Students
        description: compass all students data
      - name: STP_Centre_Identification_New_Report
        identifier: STP_Centre_Identification_New_Report
        description: STP centre identification new report
      - name: Trainer_Report
        identifier: Trainer_Report
        description: trainer report
      - name: Corporate_Catalyse_Tracker
        identifier: Corporate_Catalyse_Tracker
        description: corporate catalyse tracker
      - name: Donor_Report_Report
        identifier: Donor_Report_Report
        description: donor report report

  - name: Stem_gsheet_data
    schema: STEM_Gsheet_Raw_Data
    tables:
      - name: Consol_Y2_SCHOOLS
        identifier: Consol_Y2_SCHOOLS
        description: consolidated Y2 schools clubs data
      - name: Teacher_Details
        identifier: Teacher_Details
        description: teacher details data
      - name: Teachers_Count
        identifier: Teachers_Count
        description: teachers count data
      - name: STEM_Adv_Dtl
        identifier: STEM_Adv_Dtl
        description: STEM advanced exposure session details data
      - name: Interns_Volunteer_Tracker
        identifier: Interns_Volunteer_Tracker
        description: STP schools Interns and Volunteer Tracker data
      - name: Corporate_Volunteering_Data
        identifier: Corporate_Volunteering_Data
        description: STP schoolsCorporate Volunteering Data
      - name: STEM_FEST_X_Volunteers
        identifier: STEM_FEST_X_Volunteers
        description: STEM FEST X Volunteers data
      - name: Consolidated_TCM
        identifier: Consolidated_TCM
        description: Consolidated TCM data
      
  - name: CV_Gsheet_Raw_Data
    schema: CV_Gsheet_Raw_Data
    tables:
      - name: Form_responses
        identifier: Form_responses
        description: NPS form data
      - name: Form_responses_new
        identifier: Form_responses_new
        description: CSAT form data


  # - name: STP_25-26
  #   schema: STP_25_26_Raw_data
  #   tables:
  #     - name: All_Students
  #       identifier: All_Students
  #       description: This is a placeholder table STP 25-26
  #     - name: All_Session_Plannings
  #       identifier: All_Session_Plannings
  #       description: This is a placeholder table STP 25-26
  #     - name: All_Session_Attendances
  #       identifier: All_Session_Attendances
  #       description: This is a placeholder table STP 25-26
  #     - name: Processed_Attendance
  #       identifier: Processed_Attendance
  #       description: This is a placeholder table STP 25-26
  