version: 2

sources:
  - name: fellowship_24_25_data
    schema: fellowship_24_25
    tables:
      - name: Raw_Data_Baseline
        identifier: Raw_Data_sample
        description: This is a placeholder table & will be replaced with original. This table contains data of the baseline assessment for AY 24-25, for students in all classrooms. This table contains combined data for RF,RC & Math. This table comes from the master G-Sheet 'Baseline 2024_Overall Analysis'
      - name: Raw_Data_Midline
        identifier: Raw_Data_Midline
        description: This table contains data of the midline assessment for AY 24-25, for students in all classrooms. This table contains combined data for RF,RC & Math. This table comes from the master G-Sheet 'Midline 2024_Overall Analysis'
      - name: Raw_Data_Endline
        identifier: Raw_Data_Endline
        description: This table contains data of the endline assessment for AY 24-25, for students in all classrooms. This table contains combined data for RF,RC & Math. This table comes from the master G-Sheet 'Endline 2025_Overall data'
   
  - name: ecochamps25_26
    schema: ecochamps25_26
    tables:
      - name: Student___Session_Data
        identifier: Student___Session_Data
        description: This is a placeholder table Eco Champs 25&26
      - name: RAG_MATRIX
        identifier: RAG_MATRIX
        description: RAG_MATRIX
      - name: Data_Tracker
        identifier: Data_Tracker
        description: Data Tracker
  
  - name: fellowship_25_26
    schema: fellowship_25_26
    tables:
      - name: Raw_Data_Baseline_2025
        identifier: Raw_Data_Baseline_2025
        description: Baseline raw data for AY 25-26 (source file/name in G-Sheet or staging area)
  