-- This model selects all columns from checkins_25_26 for the last 30 days based on date_checkin
SELECT 
    id_checkin,
    city_checkin,
    date_checkin,
    TO_CHAR(date_checkin, 'Mon') AS month,
    notes_checkin,
    cohort_checkin,
    school_checkin,
    pm_name_checkin,
    fellow_id_checkin,
    new_goals_checkin,
    period_to_checkin,
    challenges_checkin,
    fellow_name_checkin,
    period_from_checkin,
    action_items_checkin,
    agenda_notes_checkin,
    is_completed_checkin,
    grade_section_checkin,
    support_needed_checkin,
    total_students_checkin,
    lesson_planning_checkin,
    reporting_period_checkin,
    next_checkin_date_checkin,
    student_engagement_checkin,
    classroom_management_checkin,
    fellow_uploaded_data_checkin,
    programme_manager_id_checkin,
    previous_goals_review_checkin,
    sel_workshop_conducted_checkin,
    teaching_effectiveness_checkin,
    professional_development_checkin
FROM {{ ref('checkins_25_26') }}
