SELECT
    id,
    city,
    ptms,
    pm_name,
    reporting_date,
    TO_CHAR(reporting_date, 'Mon') AS month,
    start_date,
    end_date,
    fellow_id,
    stem_score,
    cohort_year,
    fellow_name,
    school_name,
    helo_circles,
    grade_section,
    homes_visited,
    teaching_hours,
    total_students,
    teacher_circles,
    reporting_period,
    helo_lesson_names,
    mathematics_score,
    school_leader_checkins,
    reading_comprehension_score
FROM {{ ref('class_upd_25_26') }}
