-- This model selects all columns from ODC_25_26 for the last 30 days based on date_checkin
SELECT 
    id_odc,
    city_odc,
    date_odc,
    TO_CHAR(date_odc, 'Mon') AS month,
    cohort_odc,
    school_odc,
    pm_name_odc,
    subject_odc,
    fellow_id_odc,
    odc_notes_odc,
    strengths_odc,
    action_plan_odc,
    fellow_name_odc,
    is_completed_odc,
    lesson_topic_odc,
    grade_section_odc,
    follow_up_date_odc,
    grade_observed_odc,
    total_students_odc,
    lesson_planning_odc,
    duration_minutes_odc,
    reporting_period_odc,
    teaching_methods_odc,
    content_knowledge_odc,
    specific_feedback_odc,
    lesson_plan_review_odc,
    student_engagement_odc,
    learning_objectives_odc,
    classroom_management_odc,
    programme_manager_id_odc,
    areas_for_improvement_odc,
    assessment_techniques_odc,
    student_engagement_percentage_odc
FROM {{ ref('ODC_25_26') }}
