

WITH RC_ANALYSIS_MIDLINE AS (
    SELECT
        D.CITY_MID AS CITY,
        D.STUDENT_GRADE_MID AS GRADE,
        D.DONOR_MID AS DONOR,
        D.PM_NAME_MID AS PM_NAME,
        D.FELLOW_NAME_MID AS FELLOW_NAME,
        F.RC_MIDLINE_GROWTH_STATUS_MID AS RC_GROWTH,
        count(DISTINCT F.STUDENT_ID) AS STUDENT_COUNT_MID,
        count(DISTINCT CASE WHEN D.COHORT_MID = '2024' THEN F.STUDENT_ID END) AS COHORT_2024_COUNT_MID,
        count(DISTINCT CASE WHEN D.COHORT_MID = '2025' THEN F.STUDENT_ID END) AS COHORT_2025_COUNT_MID
    FROM 
        {{ ref('base_mid_end_comb_scores_25_26_fct') }} AS F
    INNER JOIN {{ ref('base_mid_end_comb_students_25_26_dim') }} AS D
        ON F.STUDENT_ID = D.STUDENT_ID
    WHERE D.MIDLINE_ATTENDENCE = True
    GROUP BY D.CITY_MID, D.STUDENT_GRADE_MID, F.RC_MIDLINE_GROWTH_STATUS_MID, D.DONOR_MID, D.PM_NAME_MID, D.FELLOW_NAME_MID
),

RC_ANALYSIS_ENDLINE AS (
    SELECT
        D.CITY_END AS CITY,
        D.STUDENT_GRADE_END AS GRADE,
        D.DONOR_END AS DONOR,
        D.PM_NAME_END AS PM_NAME,
        D.FELLOW_NAME_END AS FELLOW_NAME,
        F.RC_ENDLINE_GROWTH_STATUS_END AS RC_GROWTH,
        count(DISTINCT F.STUDENT_ID) AS STUDENT_COUNT_END,
        count(DISTINCT CASE WHEN D.COHORT_END = '2024' THEN F.STUDENT_ID END) AS COHORT_2024_COUNT_END,
        count(DISTINCT CASE WHEN D.COHORT_END = '2025' THEN F.STUDENT_ID END) AS COHORT_2025_COUNT_END
    FROM 
        {{ ref('base_mid_end_comb_scores_25_26_fct') }} AS F
    INNER JOIN {{ ref('base_mid_end_comb_students_25_26_dim') }} AS D
        ON F.STUDENT_ID = D.STUDENT_ID
    WHERE D.ENDLINE_ATTENDENCE = True
    GROUP BY D.CITY_END, D.STUDENT_GRADE_END, F.RC_ENDLINE_GROWTH_STATUS_END, D.DONOR_END, D.PM_NAME_END, D.FELLOW_NAME_END
),

ALL_COMBINATIONS AS (

    
    SELECT DISTINCT
        CITY,
        GRADE,
        DONOR,
        PM_NAME,
        FELLOW_NAME,
        RC_GROWTH
    FROM RC_ANALYSIS_MIDLINE
    
    union
    
    SELECT DISTINCT
        CITY,
        GRADE,
        DONOR,
        PM_NAME,
        FELLOW_NAME,
        RC_GROWTH
    FROM RC_ANALYSIS_ENDLINE

)

SELECT 
    AC.CITY,
    AC.GRADE,
    AC.DONOR,
    AC.PM_NAME,
    AC.FELLOW_NAME,
    AC.RC_GROWTH,
    M.STUDENT_COUNT_MID,
    M.COHORT_2024_COUNT_MID,
    M.COHORT_2025_COUNT_MID,
    E.STUDENT_COUNT_END,
    E.COHORT_2024_COUNT_END,
    E.COHORT_2025_COUNT_END
FROM ALL_COMBINATIONS AS AC

LEFT JOIN RC_ANALYSIS_MIDLINE AS M
    ON
        AC.CITY = M.CITY 
        AND AC.RC_GROWTH = M.RC_GROWTH 
        AND AC.GRADE = M.GRADE
        AND AC.DONOR = M.DONOR
        AND AC.PM_NAME = M.PM_NAME
        AND AC.FELLOW_NAME = M.FELLOW_NAME
left join RC_ANALYSIS_ENDLINE as E
    on 
        AC.CITY = E.CITY 
        and AC.RC_GROWTH = E.RC_GROWTH 
        and AC.GRADE = E.GRADE
        and AC.DONOR = E.DONOR
        and AC.PM_NAME = E.PM_NAME
        and AC.FELLOW_NAME = E.FELLOW_NAME
ORDER BY AC.CITY, AC.GRADE, AC.RC_GROWTH
