with endline as (
    select
        COALESCE(BTRIM("Acadamic_year"::TEXT), '') as "Acadamic year",
        COALESCE(INITCAP(BTRIM("City"::TEXT)), '') as "City",
        COALESCE(INITCAP(BTRIM("PM_Name"::TEXT)), '') as "PM Name",
        COALESCE(INITCAP(BTRIM("Donor"::TEXT)), '') as "Donor",
        COALESCE(INITCAP(BTRIM("School_Name"::TEXT)), '') as "School Name",
        COALESCE(INITCAP(BTRIM("Classroom_ID"::TEXT)), '') as "Classroom ID",
        COALESCE(INITCAP(BTRIM("Fellow_name"::TEXT)), '') as "Fellow name",
        case when BTRIM("Cohort"::TEXT) ~ '^\d+$' then ("Cohort"::TEXT)::INTEGER end as "Cohort",
        case when BTRIM("Student_grade"::TEXT) ~ '^\d+$' then ("Student_grade"::TEXT)::INTEGER end as "Student grade",
        COALESCE(BTRIM("Student_ID"::TEXT), '') as "Student ID",
        COALESCE(INITCAP(BTRIM("Student_name"::TEXT)), '') as "Student name",

        -- RC endline
        COALESCE(BTRIM("RC_level_Endline"::TEXT), '') as "RC level endline",
        NULLIF(BTRIM("RC_Grade_level_endline_"::TEXT), '') as "RC Grade level endline",
        COALESCE(BTRIM("RC_Learning_Level_status_endline"::TEXT), '') as "RC Learning Level Status endline",
        NULLIF(BTRIM("RC_Midline_Endline_Growth"::TEXT), '') as "RC Midline Endline Growth",
        COALESCE(BTRIM("RC_Endline_Growth_status"::TEXT), '') as "RC endline Growth status",

        -- RC endline Scores
        case when BTRIM("Endline_Factual"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Factual", '%','')::NUMERIC end as "Endline Factual",
        case when BTRIM("Endline_Inference"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Inference", '%','')::NUMERIC end as "Endline Inference",
        case when BTRIM("Endline_Critical_Thinking"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Critical_Thinking", '%','')::NUMERIC end as "Endline Critical Thinking",
        case when BTRIM("Endline_Vocabulary"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Vocabulary", '%','')::NUMERIC end as "Endline Vocabulary",
        case when BTRIM("Endline_Grammar"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Grammar", '%','')::NUMERIC end as "Endline Grammar",
        case when BTRIM("Endline_Assessed_Percentage"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Assessed_Percentage", '%','')::NUMERIC end as "Endline Assessed Percentage",

        -- Math endline
        COALESCE(BTRIM("Math_Level_Endline_"::TEXT), '') as "Math Level endline",
        COALESCE(BTRIM("Math_Learning_level_status_Endline"::TEXT), '') as "Math Learning Level Status endline",
        NULLIF(BTRIM("Math_Midline_Endline_Growth"::TEXT), '') as "Math Midline Endline Growth",
        COALESCE(BTRIM("Math_Endline_Growth_status"::TEXT), '') as "Math Endline Growth status",
        case when BTRIM("Math_Endline_Grade"::TEXT) ~ '^\d+$' then ("Math_Endline_Grade"::TEXT)::INTEGER end as "Math Endline Grade",
        case when BTRIM("Final_Endline_Level_Mastery"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Final_Endline_Level_Mastery", '%','')::NUMERIC end as "Final Endline Level Mastery",
        case when BTRIM("Endline_Numbers"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Numbers", '%','')::NUMERIC end as "Endline Numbers",
        case when BTRIM("Endline_Patterns"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Patterns", '%','')::NUMERIC end as "Endline Patterns",
        case when BTRIM("Endline_Geometry"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Geometry", '%','')::NUMERIC end as "Endline Geometry",
        case when BTRIM("Endline_Total_in_Mensuration"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Total_in_Mensuration", '%','')::NUMERIC end as "Endline Total in Mensuration",
        case when BTRIM("Endline_Total_in_Time"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Total_in_Time", '%','')::NUMERIC end as "Endline Total in Time",
        case when BTRIM("Endline_Total_in_Operations"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Total_in_Operations", '%','')::NUMERIC end as "Endline Total in Operations",
        case when BTRIM("Endline_Total_in_Data"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Endline_Total_in_Data", '%','')::NUMERIC end as "Endline Total in Data",

        -- RF endline
        COALESCE(BTRIM("RF_Level_Endline"::TEXT), '') as "RF Level endline",
        COALESCE(BTRIM("RF_Endline_Growth"::TEXT), '') as "RF Endline Growth",
        case when BTRIM("Endline_Letter_sounds"::TEXT) ~ '^[0-9.]+$' then ("Endline_Letter_sounds"::TEXT)::NUMERIC end as "Endline Letter sounds",
        case when BTRIM("Endline_CVC_words"::TEXT) ~ '^[0-9.]+$' then ("Endline_CVC_words"::TEXT)::NUMERIC end as "Endline CVC words",
        case when BTRIM("Endline_Blends"::TEXT) ~ '^[0-9.]+$' then ("Endline_Blends"::TEXT)::NUMERIC end as "Endline Blends",
        case when BTRIM("Endline_Consonant_diagraph"::TEXT) ~ '^[0-9.]+$' then ("Endline_Consonant_diagraph"::TEXT)::NUMERIC end as "Endline Consonant diagraph",
        case when BTRIM("Endline_Magic_E_words"::TEXT) ~ '^[0-9.]+$' then ("Endline_Magic_E_words"::TEXT)::NUMERIC end as "Endline Magic E words",
        case when BTRIM("Endline_Vowel_diagraphs"::TEXT) ~ '^[0-9.]+$' then ("Endline_Vowel_diagraphs"::TEXT)::NUMERIC end as "Endline Vowel diagraphs",
        case when BTRIM("Endline_Multi_syllabelle_words"::TEXT) ~ '^[0-9.]+$' then ("Endline_Multi_syllabelle_words"::TEXT)::NUMERIC end as "Endline Multi syllabelle words",
        case when BTRIM("Endline_Passage_1"::TEXT) ~ '^[0-9.]+$' then ("Endline_Passage_1"::TEXT)::NUMERIC end as "Endline Passage 1",
        case when BTRIM("Endline_Passage_2"::TEXT) ~ '^[0-9.]+$' then ("Endline_Passage_2"::TEXT)::NUMERIC end as "Endline Passage 2"

    from {{ source('fellowship_25_26', 'Raw_Data_Endline_2025') }}
)

select distinct
    e."Student ID" as student_id_end,
    e."Acadamic year" as acadamic_year_end,
    e."City" as city_end,
    e."PM Name" as pm_name_end,
    e."Donor" as donor_end,
    e."School Name" as school_name_end,
    e."Classroom ID" as classroom_id_end,
    e."Fellow name" as fellow_name_end,
    e."Cohort" as cohort_end,
    e."Student grade" as student_grade_end,
    e."Student name" as student_name_end,
    e."RC level endline" as rc_level_endline_end,
    e."RC Grade level endline" as rc_grade_level_endline_end,
    e."RC Learning Level Status endline" as rc_learning_level_status_endline_end,
    e."RC Midline Endline Growth" as rc_midline_endline_growth_end,
    e."RC endline Growth status" as rc_endline_growth_status_end,
    e."Endline Factual" as endline_factual_end,
    e."Endline Inference" as endline_inference_end,
    e."Endline Critical Thinking" as endline_critical_thinking_end,
    e."Endline Vocabulary" as endline_vocabulary_end,
    e."Endline Grammar" as endline_grammar_end,
    e."Endline Assessed Percentage" as endline_assessed_percentage_end,
    e."Math Level endline" as math_level_endline_end,
    e."Math Endline Grade" as math_endline_grade_end,
    e."Math Learning Level Status endline" as math_learning_level_status_endline_end,
    e."Math Midline Endline Growth" as math_midline_endline_growth_end,
    e."Math Endline Growth status" as math_endline_growth_status_end,
    e."Final Endline Level Mastery" as final_endline_level_mastery_end,
    e."Endline Numbers" as endline_numbers_end,
    e."Endline Patterns" as endline_patterns_end,
    e."Endline Geometry" as endline_geometry_end,
    e."Endline Total in Mensuration" as endline_total_in_mensuration_end,
    e."Endline Total in Time" as endline_total_in_time_end,
    e."Endline Total in Operations" as endline_total_in_operations_end,
    e."Endline Total in Data" as endline_total_in_data_end,
    e."RF Level endline" as rf_level_endline_end,
    e."RF Endline Growth" as rf_endline_growth_end,
    e."Endline Letter sounds" as endline_letter_sounds_end,
    e."Endline CVC words" as endline_cvc_words_end,
    e."Endline Blends" as endline_blends_end,
    e."Endline Consonant diagraph" as endline_consonant_diagraph_end,
    e."Endline Magic E words" as endline_magic_e_words_end,
    e."Endline Vowel diagraphs" as endline_vowel_diagraphs_end,
    e."Endline Multi syllabelle words" as endline_multi_syllabelle_words_end,
    e."Endline Passage 1" as endline_passage_1_end,
    e."Endline Passage 2" as endline_passage_2_end
from endline as e
where e."Student ID" <> ''
