with midline as (
    select
        COALESCE(BTRIM("Acadamic_year"::TEXT), '') as "Acadamic year",
        COALESCE(INITCAP(BTRIM("City"::TEXT)), '') as "City",
        COALESCE(INITCAP(BTRIM("PM_Name"::TEXT)), '') as "PM Name",
        COALESCE(INITCAP(BTRIM("School_Name"::TEXT)), '') as "School Name",
        COALESCE(INITCAP(BTRIM("Classroom_ID"::TEXT)), '') as "Classroom ID",
        COALESCE(INITCAP(BTRIM("Fellow_name"::TEXT)), '') as "Fellow name",
        case when BTRIM("Cohort"::TEXT) ~ '^\d+$' then ("Cohort"::TEXT)::INTEGER end as "Cohort",
        case when BTRIM("Student_grade"::TEXT) ~ '^\d+$' then ("Student_grade"::TEXT)::INTEGER end as "Student grade",
        COALESCE(BTRIM("Student_ID"::TEXT), '') as "Student ID",
        COALESCE(INITCAP(BTRIM("Student_name"::TEXT)), '') as "Student name",

        -- RC Midline
        COALESCE(BTRIM("RC_level_Midline"::TEXT), '') as "RC level Midline",
        COALESCE(BTRIM("RC_Grade_level_Midline_"::TEXT), '') as "RC Grade level Midline",
        COALESCE(BTRIM("RC_Learning_Level_status_Midline"::TEXT), '') as "RC Learning Level Status Midline",
        NULLIF(BTRIM("RC_Baseline_Midline_Growth"::TEXT), '') as "RC Baseline Midline Growth",

        -- RC Midline Scores
        case when BTRIM("Midline_Factual"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Factual", '%','')::NUMERIC end as "Midline Factual",
        case when BTRIM("Midline_Inference"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Inference", '%','')::NUMERIC end as "Midline Inference",
        case when BTRIM("Midline_Critical_Thinking"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Critical_Thinking", '%','')::NUMERIC end as "Midline Critical Thinking",
        case when BTRIM("Midline_Vocabulary"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Vocabulary", '%','')::NUMERIC end as "Midline Vocabulary",
        case when BTRIM("Midline_Grammar"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Grammar", '%','')::NUMERIC end as "Midline Grammar",
        case when BTRIM("Midline_Assessed_Percentage"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Assessed_Percentage", '%','')::NUMERIC end as "Midline Assessed Percentage",

        -- Math Midline
        COALESCE(BTRIM("Math_Level_Midline_"::TEXT), '') as "Math Level Midline",
        case when BTRIM("Final_Midline_Level_Mastery"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Final_Midline_Level_Mastery", '%','')::NUMERIC end as "Final Midline Level Mastery",
        case when BTRIM("Math_Midline_Grade"::TEXT) ~ '^\d+$' then ("Math_Midline_Grade"::TEXT)::INTEGER end as "Math Midline Grade",
        COALESCE(BTRIM("Math_Learning_level_status_Midline"::TEXT), '') as "Math Learning Level Status Midline",
        NULLIF(BTRIM("Math_Baseline_Midline_Growth"::TEXT), '') as "Math Baseline Midline Growth",
        case when BTRIM("Midline_Numbers"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Numbers", '%','')::NUMERIC end as "Midline Numbers",
        case when BTRIM("Midline_Patterns"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Patterns", '%','')::NUMERIC end as "Midline Patterns",
        case when BTRIM("Midline_Geometry"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Geometry", '%','')::NUMERIC end as "Midline Geometry",
        case when BTRIM("Midline_Total_in_Mensuration"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Total_in_Mensuration", '%','')::NUMERIC end as "Midline Total in Mensuration",
        case when BTRIM("Midline_Total_in_Time"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Total_in_Time", '%','')::NUMERIC end as "Midline Total in Time",
        case when BTRIM("Midline_Total_in_Operations"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Total_in_Operations", '%','')::NUMERIC end as "Midline Total in Operations",
        case when BTRIM("Midline_Total_in_Data"::TEXT) ~ '^[0-9.]+%?$' then REPLACE("Midline_Total_in_Data", '%','')::NUMERIC end as "Midline Total in Data",

        -- RF Midline
        COALESCE(BTRIM("RF_Level_midline"::TEXT), '') as "RF Level Midline",
        NULLIF(BTRIM("RF_Midline_Growth"::TEXT), '') as "RF Midline Growth",
        case when BTRIM("Midline_Letter_sounds"::TEXT) ~ '^[0-9.]+$' then ("Midline_Letter_sounds"::TEXT)::NUMERIC end as "Midline Letter sounds",
        case when BTRIM("Midline_CVC_words"::TEXT) ~ '^[0-9.]+$' then ("Midline_CVC_words"::TEXT)::NUMERIC end as "Midline CVC words",
        case when BTRIM("Midline_Blends"::TEXT) ~ '^[0-9.]+$' then ("Midline_Blends"::TEXT)::NUMERIC end as "Midline Blends",
        case when BTRIM("Midline_Consonant_diagraph"::TEXT) ~ '^[0-9.]+$' then ("Midline_Consonant_diagraph"::TEXT)::NUMERIC end as "Midline Consonant diagraph",
        case when BTRIM("Midline_Magic_E_words"::TEXT) ~ '^[0-9.]+$' then ("Midline_Magic_E_words"::TEXT)::NUMERIC end as "Midline Magic E words",
        case when BTRIM("Midline_Vowel_diagraphs"::TEXT) ~ '^[0-9.]+$' then ("Midline_Vowel_diagraphs"::TEXT)::NUMERIC end as "Midline Vowel diagraphs",
        case when BTRIM("Midline_Multi_syllabelle_words"::TEXT) ~ '^[0-9.]+$' then ("Midline_Multi_syllabelle_words"::TEXT)::NUMERIC end as "Midline Multi syllabelle words",
        case when BTRIM("Midline_Passage_1"::TEXT) ~ '^[0-9.]+$' then ("Midline_Passage_1"::TEXT)::NUMERIC end as "Midline Passage 1",
        case when BTRIM("Midline_Passage_2"::TEXT) ~ '^[0-9.]+$' then ("Midline_Passage_2"::TEXT)::NUMERIC end as "Midline Passage 2"

    from {{ source('fellowship_25_26', 'Raw_Data_Midline_2025') }}
)

select distinct
    m."Student ID" as student_id_mid,
    m."Acadamic year" as acadamic_year_mid,
    m."City" as city_mid,
    m."PM Name" as pm_name_mid,
    m."School Name" as school_name_mid,
    m."Classroom ID" as classroom_id_mid,
    m."Fellow name" as fellow_name_mid,
    m."Cohort" as cohort_mid,
    m."Student grade" as student_grade_mid,
    m."Student name" as student_name_mid,
    m."RC level Midline" as rc_level_midline_mid,
    m."RC Grade level Midline" as rc_grade_level_midline_mid,
    m."RC Learning Level Status Midline" as rc_learning_level_status_midline_mid,
    m."RC Baseline Midline Growth" as rc_baseline_midline_growth_mid,
    m."Midline Factual" as midline_factual_mid,
    m."Midline Inference" as midline_inference_mid,
    m."Midline Critical Thinking" as midline_critical_thinking_mid,
    m."Midline Vocabulary" as midline_vocabulary_mid,
    m."Midline Grammar" as midline_grammar_mid,
    m."Midline Assessed Percentage" as midline_assessed_percentage_mid,
    m."Math Level Midline" as math_level_midline_mid,
    m."Math Midline Grade" as math_midline_grade_mid,
    m."Math Learning Level Status Midline" as math_learning_level_status_midline_mid,
    m."Math Baseline Midline Growth" as math_baseline_midline_growth_mid,
    m."Final Midline Level Mastery" as final_midline_level_mastery_mid,
    m."Midline Numbers" as midline_numbers_mid,
    m."Midline Patterns" as midline_patterns_mid,
    m."Midline Geometry" as midline_geometry_mid,
    m."Midline Total in Mensuration" as midline_total_in_mensuration_mid,
    m."Midline Total in Time" as midline_total_in_time_mid,
    m."Midline Total in Operations" as midline_total_in_operations_mid,
    m."Midline Total in Data" as midline_total_in_data_mid,
    m."RF Level Midline" as rf_level_midline_mid,
    m."RF Midline Growth" as rf_midline_growth_mid,
    m."Midline Letter sounds" as midline_letter_sounds_mid,
    m."Midline CVC words" as midline_cvc_words_mid,
    m."Midline Blends" as midline_blends_mid,
    m."Midline Consonant diagraph" as midline_consonant_diagraph_mid,
    m."Midline Magic E words" as midline_magic_e_words_mid,
    m."Midline Vowel diagraphs" as midline_vowel_diagraphs_mid,
    m."Midline Multi syllabelle words" as midline_multi_syllabelle_words_mid,
    m."Midline Passage 1" as midline_passage_1_mid,
    m."Midline Passage 2" as midline_passage_2_mid
from midline as m
where m."Student ID" <> ''
